## Default Database Properties (In memory H2)
spring:
  h2:
    console:
      enabled: true
      path: /h2 # http://localhost:8080/h2 and input the URL and username below (no password required)
  datasource:
    url: jdbc:h2:mem:bugout
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



# BANNER
spring.banner.location: classpath:banner.txt

# ENDPOINT MANAGEMENT
management:
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"



