create table ISSUES (
                        ID int generated by default as identity not null,
                        TITLE varchar(50) not null,
                        DESCRIPTION varchar(255),
                        CREATIONDATE date,
                        DEVELOPERID int,
                        TYPE smallint not null,
                        STATUS smallint not null,
                        PRIORITY smallint,
                        POINT smallint,
                        ASSIGNEDWEEK smallint,
                        primary key (ID)
);
create table DEVELOPERS (
                            ID int generated by default as identity not null,
                            NAME text not null,
                            primary key (ID)
);
insert into DEVELOPERS (NAME)
<<<<<<< HEAD
values ('Test Developer 1');
insert into DEVELOPERS (NAME)
values ('Test Developer 2');
insert into DEVELOPERS (NAME)
values ('Test Developer 3');
=======
values ('Lyle Christine');
insert into DEVELOPERS (NAME)
values ('Jimmy James');
insert into DEVELOPERS (NAME)
values ('Hendo Henson');
>>>>>>> restoration of broken app
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           1,
<<<<<<< HEAD
           'test bug 1',
           'bug 1 description',
           '2016-09-03 00:00:00',
           2,
=======
           'Update JDBC connection',
           'The JDBC username and password values in the application.properties file need updated with the new credentials.',
           '2021-10-12 15:00:00',
           1,
>>>>>>> restoration of broken app
           1,
           3,
           1,
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           2,
<<<<<<< HEAD
           'test bug 2',
           'bug 2 description',
           '2016-09-03 00:00:00',
           1,
=======
           'Change Maven version in Dockerfile',
           'The Maven image version in the DOckerfile is currently 3.5.1 - this should be updated to 3.6.2.',
           '2021-10-03 13:00:00',
           3,
>>>>>>> restoration of broken app
           1,
           2,
           3,
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           3,
<<<<<<< HEAD
           'test bug 3',
           'bug 3 description',
           '2016-09-03 00:00:00',
           2,
           1,
           1,
           2,
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           4,
           'test bug 4',
           'bug 4 description',
           '2016-09-03 00:00:00',
           1,
           1,
           2,
           1,
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           5,
           'test bug 5',
           'bug 5 description',
           '2016-09-03 00:00:00',
           1,
           1,
           3,
           3,
=======
           'Fix failing unit test in CustomerServiceTest.java',
           'The final unit test in CustomerServiceTest.java is failing after recent update. Investigate and fix.',
           '2021-10-09 14:00:00',
           2,
           1,
           1,
           2,
>>>>>>> restoration of broken app
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT,
    ASSIGNEDWEEK
)
values (
           6,
<<<<<<< HEAD
           'test story 1',
           'story 1 description',
           '2016-09-03 00:00:00',
=======
           'PoC : funneling data through Debezium into Kafka',
           'Create a proof-of-concept of funneling database events from the CustomerDetails schema into Kafka, using a Debezium connection.',
           '2021-10-05 17:00:00',
>>>>>>> restoration of broken app
           1,
           2,
           3,
           null,
           1,
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT,
    ASSIGNEDWEEK
)
values (
           7,
<<<<<<< HEAD
           'test story 2',
           'story 2 description',
           '2016-09-03 00:00:00',
=======
           'Deploy Spring Boot app with React frontend as embedded component',
           'Using the maven-frontend-plugin, move the React frontend into src/main/webapp and deploy the Spring Boot backend and React frontend as an embedded application.',
           '2021-10-07 14:30:00',
>>>>>>> restoration of broken app
           2,
           2,
           2,
           null,
           2,
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT,
    ASSIGNEDWEEK
)
values (
           8,
<<<<<<< HEAD
           'test story 3',
           'story 3 description',
           '2016-09-03 00:00:00',
=======
           'PoC - Investigate using Quarkus over Spring Boot',
           'Quarkus has lower I/O overheads which could lower cloud costs. Investigate the potential benefits of migrating our Spring Boot microservices to Quarkus.',
           '2021-10-02 09:00:00',
>>>>>>> restoration of broken app
           3,
           2,
           2,
           null,
           3,
           null
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           9,
<<<<<<< HEAD
           'test story 4',
           'story 4 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           5
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           10,
           'test story 5',
           'story 5 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           8
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           11,
           'test story 6',
           'story 6 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           8
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           12,
           'test story 7',
           'story 7 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           2
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           13,
           'test story 8',
           'story 8 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           3
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           14,
           'test story 9',
           'story 9 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           5
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           15,
           'test story 10',
           'story 10 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           8
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           16,
           'test story 11',
           'story 11 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           1
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           17,
           'test story 12',
           'story 12 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           2
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           18,
           'test story 13',
           'story 13 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           3
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           19,
           'test story 14',
           'story 14 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           8
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           20,
           'test story 15',
           'story 15 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           8
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           21,
           'test story 16',
           'story 16 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           1
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           22,
           'test story 17',
           'story 17 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           2
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           23,
           'test story 18',
           'story 18 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           2
       );
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           24,
           'test story 19',
           'story 19 description',
           '2016-09-03 00:00:00',
           null,
           2,
=======
           'BitBucket to GitHub migration - Flask app and automation scripts',
           'Build a Python/Flask app to automate migrating our code repos from BitBucket to GitHUb.',
           '2021-10-01 10:20:00',
           null,
           1,
>>>>>>> restoration of broken app
           2,
           null,
           5
       );
<<<<<<< HEAD
insert into ISSUES (
    ID,
    TITLE,
    DESCRIPTION,
    CREATIONDATE,
    DEVELOPERID,
    TYPE,
    STATUS,
    PRIORITY,
    POINT
)
values (
           25,
           'test story 20',
           'story 20 description',
           '2016-09-03 00:00:00',
           null,
           2,
           2,
           null,
           8
       );
=======




>>>>>>> restoration of broken app
